name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # This is a pre-made GitHub Action for checking out a repo

      - name: Set Up Git user
        run: |
          git config --local user.name "meiostdio@gmail.com"
          git config --local user.name "meiostdio"

      - name: Deploy ğŸš€
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git checkout -b gh-pages
          cp -R HP/* .
          git add .
          git commit -m "Automated GitHub Pages deployment"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/meiostdio/HPv2.git gh-pages --force
