name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2 # This is a pre-made GitHub Action for checking out a repo

      - name: Set Up Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Deploy üöÄ
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git checkout -b gh-pages
          cp -R HP/* .
          git add .
          git commit -m "Automated GitHub Pages deployment"
          if [[ -n "$GITHUB_TOKEN" ]]; then
            git push https://${GITHUB_TOKEN}@github.com/meiostdio/HPv2.git gh-pages
          else
            echo "GITHUB_TOKEN is not set. Skipping push."
          fi
