name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Set Up Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # HP ãƒ•ã‚©ãƒ«ãƒ€ã‚’ä¸€æ™‚ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã«ã‚³ãƒ”ãƒ¼
      - name: Copy HP directory to temporary directory
        run: |
          mkdir temp_directory
          cp -R HP/* temp_directory/

      # gh-pages ãƒ–ãƒ©ãƒ³ãƒã«åˆ‡ã‚Šæ›¿ãˆã¦
      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git rm -rf *
          git checkout -b gh-pages --track origin/gh-pages

      # ä¸€æ™‚ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‹ã‚‰ã‚³ãƒ”ãƒ¼
      - name: Copy files to gh-pages branch
        run: |
          cp -R temp_directory/* .

      - name: Delete temp_directory from gh-pages branch
        run: |
          rm -rf temp_directory

      - name: Commit
        run: |
          git add .
          git commit -m "Automated GitHub Pages deployment"

      # Push
      - name: Push to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git push https://${GITHUB_TOKEN}@github.com/meiostdio/HPv2.git gh-pages --force

  depoy-to-vercel:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm --name meiostdio
